[package]
name = "digby"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.4"
rand = "0.9.2"
tempfile = "3.22.0"
xxhash-rust = { version = "0.8.15", features = ["xxh32"] }
sha2 = "0.10"

[lib]
path = "src/lib.rs"
